### ISSUE TITLE
Ubnutu 构建dodcker 镜像出错。。这是咋回事呢 老哥

### ISSUE THREAD

**Issue by skykiah** [jagerzhang/flyer#3]
`root@iZbp15z3tk2zh140a3qu1cZ:~# ls
data  Fastapi  fastgpt  FastGPT  flyer  node_modules  package.json  package-lock.json  __pycache__  x-ui
root@iZbp15z3tk2zh140a3qu1cZ:~# cd flyer
root@iZbp15z3tk2zh140a3qu1cZ:~/flyer# docker build -t "flyer:test" .

[+] Building 1.3s (7/12)                                                                                          
 => [internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 1.33kB                                                                       0.0s
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 42B                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                           0.9s
 => [1/8] FROM docker.io/library/python:3.8-slim@sha256:10e07e36f86af4371accc42642852aa60eab74e6896fc065345  0.0s
 => [internal] load build context                                                                            0.1s
 => => transferring context: 2.97MB                                                                          0.1s
 => CACHED [2/8] WORKDIR /flyer                                                                              0.0s
 => ERROR [3/8] RUN sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/' /etc/apt/sources.list &&     apt-g  0.4s
------                                                                                                            
 > [3/8] RUN sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/' /etc/apt/sources.list &&     apt-get update &&     apt-get install make automake gcc g++ python3-dev curl default-libmysqlclient-dev net-tools -y &&     apt-get clean:
#0 0.271 sed: can't read /etc/apt/sources.list: No such file or directory
------
Dockerfile:18
--------------------
  17 |     
  18 | >>> RUN sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/' /etc/apt/sources.list && \
  19 | >>>     apt-get update && \
  20 | >>>     apt-get install make automake gcc g++ python3-dev curl default-libmysqlclient-dev net-tools -y && \
  21 | >>>     apt-get clean
  22 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/' /etc/apt/sources.list &&     apt-get update &&     apt-get install make automake gcc g++ python3-dev curl default-libmysqlclient-dev net-tools -y &&     apt-get clean" did not complete successfully: exit code: 2
`

**Comment by jagerzhang** [comment]
Dockerfile内容改过么？如果没改过应该没问题吧，我刚还编译试了下

**Comment by jagerzhang** [comment]
直接在源码目录 docker build  没什么问题...
